;(function($,window,document,undefined){var Animation=function(Glide,Core){var offset;function Animation(){}
Animation.prototype.make=function(displacement){if(!Core.Run.canProcess()){return Core.Arrows.disable();}
offset=(typeof displacement!=='undefined')?parseInt(displacement):0;this[Glide.options.type]();return this;};Animation.prototype.after=function(callback){return setTimeout(function(){callback();},Glide.options.animationDuration+20);};Animation.prototype.slider=function(){var translate=Glide[Glide.size]*(Glide.current-1);var shift=Core.Clones.shift-Glide.paddings;if(Core.Run.isStart()){if(Glide.options.centered){shift=Math.abs(shift);}
else{shift=0;}
Core.Arrows.disable('prev');}
else if(Core.Run.isEnd()){if(Glide.options.centered){shift=Math.abs(shift);}
else{shift=Math.abs(shift*2);}
Core.Arrows.disable('next');}
else{shift=Math.abs(shift);Core.Arrows.enable();}
Glide.track.css({'transition':Core.Transition.get('all'),'transform':Core.Translate.set(Glide.axis,translate-shift-offset)});};Animation.prototype.carousel=function(){var translate=Glide[Glide.size]*Glide.current;var shift;if(Glide.options.centered){shift=Core.Clones.shift-Glide.paddings;}else{shift=Core.Clones.shift;}
if(Core.Run.isOffset('<')){translate=0;Core.Run.flag=false;this.after(function(){Glide.track.css({'transition':Core.Transition.clear('all'),'transform':Core.Translate.set(Glide.axis,Glide[Glide.size]*Glide.length+shift)});});}
if(Core.Run.isOffset('>')){translate=(Glide[Glide.size]*Glide.length)+Glide[Glide.size];Core.Run.flag=false;this.after(function(){Glide.track.css({'transition':Core.Transition.clear('all'),'transform':Core.Translate.set(Glide.axis,Glide[Glide.size]+shift)});});}
Glide.track.css({'transition':Core.Transition.get('all'),'transform':Core.Translate.set(Glide.axis,translate+shift-offset)});};Animation.prototype.slideshow=function(){Glide.slides.css('transition',Core.Transition.get('opacity')).eq(Glide.current-1).css('opacity',1).siblings().css('opacity',0);};return new Animation();};;var Api=function(Glide,Core){function Api(){}
Api.prototype.instance=function(){return{current:function(){return Glide.current;},go:function(distance,callback){Core.Run.pause();Core.Run.make(distance,callback);Core.Run.play();},jump:function(distance,callback){Core.Transition.jumping=true;Core.Animation.after(function(){Core.Transition.jumping=false;});Core.Run.make(distance,callback);},move:function(distance){Core.Transition.jumping=true;Core.Animation.make(distance);Core.Transition.jumping=false;},start:function(interval){Core.Run.running=true;Glide.options.autoplay=parseInt(interval);Core.Run.play();},play:function(){return Core.Run.play();},pause:function(){return Core.Run.pause();},destroy:function(){Core.Run.pause();Core.Clones.remove();Core.Helper.removeStyles([Glide.track,Glide.slides]);Core.Bullets.remove();Glide.slider.removeData('glide_api');Core.Events.unbind();Core.Touch.unbind();Core.Arrows.unbind();Core.Bullets.unbind();Glide.destroyed=true;delete Glide.slider;delete Glide.track;delete Glide.slides;delete Glide.width;delete Glide.length;},refresh:function(){Core.Run.pause();Glide.collect();Glide.setup();Core.Clones.remove().init();Core.Bullets.remove().init();Core.Build.init();Core.Run.make('='+parseInt(Glide.options.startAt),Core.Run.play());},};};return new Api();};;var Arrows=function(Glide,Core){function Arrows(){this.build();this.bind();}
Arrows.prototype.build=function(){this.wrapper=Glide.slider.find('.'+Glide.options.classes.arrows);this.items=this.wrapper.children();};Arrows.prototype.disable=function(type){var classes=Glide.options.classes;if(!type){return this.disableBoth();}
this.items.filter('.'+classes['arrow'+Core.Helper.capitalise(type)]).unbind('click.glide touchstart.glide').addClass(classes.disabled).siblings().bind('click.glide touchstart.glide',this.click).bind('mouseenter.glide',this.hover).bind('mouseleave.glide',this.hover).removeClass(classes.disabled);};Arrows.prototype.disableBoth=function(){this.items.unbind('click.glide touchstart.glide').addClass(Glide.options.classes.disabled);};Arrows.prototype.enable=function(){this.bind();this.items.removeClass(Glide.options.classes.disabled);};Arrows.prototype.click=function(event){event.preventDefault();if(!Core.Events.disabled){Core.Run.pause();Core.Run.make($(this).data('glide-dir'));Core.Animation.after(function(){Core.Run.play();});}};Arrows.prototype.hover=function(event){if(!Core.Events.disabled){switch(event.type){case'mouseleave':Core.Run.play();break;case'mouseenter':Core.Run.pause();break;}}};Arrows.prototype.bind=function(){this.items.on('click.glide touchstart.glide',this.click).on('mouseenter.glide',this.hover).on('mouseleave.glide',this.hover);};Arrows.prototype.unbind=function(){this.items.off('click.glide touchstart.glide').off('mouseenter.glide').off('mouseleave.glide');};return new Arrows();};;var Build=function(Glide,Core){function Build(){this.init();}
Build.prototype.init=function(){this[Glide.options.type]();this.active();Core.Height.set();};Build.prototype.isType=function(name){return Glide.options.type===name;};Build.prototype.isMode=function(name){return Glide.options.mode===name;};Build.prototype.slider=function(){Core.Transition.jumping=true;Glide.slides[Glide.size](Glide[Glide.size]);Glide.track.css(Glide.size,Glide[Glide.size]*Glide.length);if(this.isMode('vertical')){Core.Height.set(true);}
Core.Animation.make();Core.Transition.jumping=false;};Build.prototype.carousel=function(){Core.Transition.jumping=true;Core.Clones.shift=(Glide[Glide.size]*Core.Clones.items.length/2)-Glide[Glide.size];Glide.slides[Glide.size](Glide[Glide.size]);Glide.track.css(Glide.size,(Glide[Glide.size]*Glide.length)+Core.Clones.getGrowth());if(this.isMode('vertical')){Core.Height.set(true);}
Core.Animation.make();Core.Clones.append();Core.Transition.jumping=false;};Build.prototype.slideshow=function(){Core.Transition.jumping=true;Core.Animation.make();Core.Transition.jumping=false;};Build.prototype.active=function(){Glide.slides.eq(Glide.current-1).addClass(Glide.options.classes.active).siblings().removeClass(Glide.options.classes.active);};return new Build();};;var Bullets=function(Glide,Core){function Bullets(){this.init();this.bind();}
Bullets.prototype.init=function(){this.build();this.active();return this;};Bullets.prototype.build=function(){this.wrapper=Glide.slider.children('.'+Glide.options.classes.bullets);for(var i=1;i<=Glide.length;i++){$('<button>',{'class':Glide.options.classes.bullet,'data-glide-dir':'='+i}).appendTo(this.wrapper);}
this.items=this.wrapper.children();};Bullets.prototype.active=function(){this.items.eq(Glide.current-1).addClass('active').siblings().removeClass('active');};Bullets.prototype.remove=function(){this.items.remove();return this;};Bullets.prototype.click=function(event){event.preventDefault();if(!Core.Events.disabled){Core.Run.pause();Core.Run.make($(this).data('glide-dir'));Core.Animation.after(function(){Core.Run.play();});}};Bullets.prototype.hover=function(event){if(!Core.Events.disabled){switch(event.type){case'mouseleave':Core.Run.play();break;case'mouseenter':Core.Run.pause();break;}}};Bullets.prototype.bind=function(){this.wrapper.on('click.glide touchstart.glide','button',this.click).on('mouseenter.glide','button',this.hover).on('mouseleave.glide','button',this.hover);};Bullets.prototype.unbind=function(){this.wrapper.off('click.glide touchstart.glide','button').off('mouseenter.glide','button').off('mouseleave.glide','button');};return new Bullets();};;var Clones=function(Glide,Core){var map=[0,1];var pattern;function Clones(){this.items=[];this.shift=0;this.init();}
Clones.prototype.init=function(){this.map();this.collect();return this;};Clones.prototype.map=function(){var i;pattern=[];for(i=0;i<map.length;i++){pattern.push(-1-i,i);}};Clones.prototype.collect=function(){var item;var i;for(i=0;i<pattern.length;i++){item=Glide.slides.eq(pattern[i]).clone().addClass(Glide.options.classes.clone);this.items.push(item);}};Clones.prototype.append=function(){var i;var item;for(i=0;i<this.items.length;i++){item=this.items[i][Glide.size](Glide[Glide.size]);if(pattern[i]>=0){item.appendTo(Glide.track);}else{item.prependTo(Glide.track);}}};Clones.prototype.remove=function(){var i;for(i=0;i<this.items.length;i++){this.items[i].remove();}
return this;};Clones.prototype.getGrowth=function(){return Glide.width*this.items.length;};return new Clones();};;var Core=function(Glide,Modules){function Core(){for(var module in Modules){this[module]=new Modules[module](Glide,this);}}
return new Core();};;var Events=function(Glide,Core){var triggers=$('[data-glide-trigger]');function Events(){this.disabled=false;this.prevented=false;this.keyboard();this.hoverpause();this.resize();this.bindTriggers();this.bindAnchors();this.bindImages();}
Events.prototype.keyboard=function(){if(Glide.options.keyboard){$(window).on('keyup.glide',function(event){if(event.keyCode===39){Core.Run.make('>');}
if(event.keyCode===37){Core.Run.make('<');}});}};Events.prototype.hoverpause=function(){if(Glide.options.hoverpause){Glide.track.on('mouseover.glide',function(){Core.Run.pause();Core.Events.trigger('mouseOver');}).on('mouseout.glide',function(){Core.Run.play();Core.Events.trigger('mouseOut');});}};Events.prototype.resize=function(){$(window).on('resize.glide.'+Glide.uuid,Core.Helper.throttle(function(){if(!Glide.destroyed){Core.Transition.jumping=true;Glide.setup();Core.Build.init();Core.Run.make('='+Glide.current,false);Core.Run.play();Core.Transition.jumping=false;}},Glide.options.throttle));};Events.prototype.bindTriggers=function(){if(triggers.length){triggers.off('click.glide touchstart.glide').on('click.glide touchstart.glide',this.handleTrigger);}};Events.prototype.handleTrigger=function(event){event.preventDefault();var targets=$(this).data('glide-trigger').split(" ");if(!this.disabled){for(var el in targets){var target=$(targets[el]).data('glide_api');target.pause();target.go($(this).data('glide-dir'),this.activeTrigger);target.play();}}};Events.prototype.bindAnchors=function(){Glide.track.on('click.glide','a',function(e){if(this.prevented){e.preventDefault();}}.bind(this));};Events.prototype.bindImages=function(){Glide.track.on('dragstart.glide','img',function(e){if(this.prevented){e.preventDefault();}}.bind(this));};Events.prototype.detachClicks=function(event){Glide.track.find('a').each(function(i,a){$(a).attr('data-href',$(a).attr('href')).removeAttr('href');});return this;};Events.prototype.attachClicks=function(event){Glide.track.find('a').each(function(i,a){$(a).attr('href',$(a).attr('data-href')).removeAttr('data-href');});Core.Animation.after(function(){this.prevented=false;}.bind(this));return this;};Events.prototype.preventClicks=function(){this.prevented=true;return this;};Events.prototype.call=function(func){if((func!=='undefined')&&(typeof func==='function')){func(this.getParams());}
return this;};Events.prototype.trigger=function(name){Glide.slider.trigger(name+".glide",[this.getParams()]);return this;};Events.prototype.getParams=function(){return{index:Glide.current,length:Glide.slides.length,current:Glide.slides.eq(Glide.current-1),slider:Glide.slider,swipe:{distance:(Core.Touch.distance||0)}};};Events.prototype.unbind=function(){Glide.track.off('click.glide','a').off('dragstart.glide','img').off('keyup.glide').off('mouseover.glide').off('mouseout.glide');triggers.off('click.glide touchstart.glide');$(window).off('keyup.glide').off('resize.glide.'+Glide.uuid);};Events.prototype.disable=function(){this.disabled=true;return this;};Events.prototype.enable=function(){this.disabled=false;return this;};return new Events();};;var Height=function(Glide,Core){function Height(){if(Glide.options.autoheight){Glide.wrapper.css({'transition':Core.Transition.get('height'),});}}
Height.prototype.get=function(){var offset=(Glide.axis==='y')?Glide.paddings*2:0;return Glide.slides.eq(Glide.current-1).height()+offset;};Height.prototype.set=function(force){return(Glide.options.autoheight||force)?Glide.wrapper.height(this.get()):false;};return new Height();};;var Helper=function(Glide,Core){function Helper(){}
Helper.prototype.byAxis=function(hValue,vValue){if(Glide.axis==='y'){return vValue;}
return hValue;};Helper.prototype.capitalise=function(string){return string.charAt(0).toUpperCase()+string.slice(1);};Helper.prototype.now=Date.now||function(){return new Date().getTime();};Helper.prototype.throttle=function(func,wait,options){var that=this;var context;var args;var result;var timeout=null;var previous=0;if(!options){options={};}
var later=function(){previous=options.leading===false?0:that.now();timeout=null;result=func.apply(context,args);if(!timeout){context=args=null;}};return function(){var now=that.now();if(!previous&&options.leading===false){previous=now;}
var remaining=wait-(now-previous);context=this;args=arguments;if(remaining<=0||remaining>wait){if(timeout){clearTimeout(timeout);timeout=null;}
previous=now;result=func.apply(context,args);if(!timeout){context=args=null;}}else if(!timeout&&options.trailing!==false){timeout=setTimeout(later,remaining);}
return result;};};Helper.prototype.removeStyles=function(elements){for(var i=0;i<elements.length;i++){elements[i].removeAttr('style');}};return new Helper();};;var Run=function(Glide,Core){function Run(){this.running=false;this.flag=false;this.play();}
Run.prototype.play=function(){var that=this;if(!this.canProcess()){return;}
if(Glide.options.autoplay||this.running){if(typeof this.interval==='undefined'){this.interval=setInterval(function(){that.pause();that.make('>');that.play();},this.getInterval());}}
return this.interval;};Run.prototype.getInterval=function(){return parseInt(Glide.slides.eq(Glide.current-1).data('glide-autoplay'))||Glide.options.autoplay;};Run.prototype.pause=function(){if(Glide.options.autoplay||this.running){if(this.interval>=0){this.interval=clearInterval(this.interval);}}
return this.interval;};Run.prototype.isStart=function(){return Glide.current===1;};Run.prototype.isEnd=function(){return Glide.current===Glide.length;};Run.prototype.isOffset=function(direction){return this.flag&&this.direction===direction;};Run.prototype.make=function(move,callback){var that=this;this.direction=move.substr(0,1);this.steps=(move.substr(1))?move.substr(1):0;if(!this.canProcess()){return this.stop();}
if(!Glide.options.hoverpause){this.pause();}
if(callback!==false){Core.Events.disable().call(Glide.options.beforeTransition).trigger('beforeTransition');}
switch(this.direction){case'>':if(this.isEnd()){Glide.current=1;this.flag=true;}
else if(this.steps==='>'){Glide.current=Glide.length;}
else{Glide.current=Glide.current+1;}
break;case'<':if(this.isStart()){Glide.current=Glide.length;this.flag=true;}
else if(this.steps==='<'){Glide.current=1;}
else{Glide.current=Glide.current-1;}
break;case'=':Glide.current=parseInt(this.steps);break;}
Core.Height.set();Core.Bullets.active();Core.Animation.make().after(function(){Core.Build.active();if(callback!==false){Core.Events.enable().call(callback).call(Glide.options.afterTransition).trigger('afterTransition');}
if(!Glide.options.hoverpause){that.play();}});Core.Events.call(Glide.options.duringTransition).trigger('duringTransition');};Run.prototype.stop=function(){this.pause();};Run.prototype.canProcess=function(){return Glide.slides.length>1;};return new Run();};;var Touch=function(Glide,Core){var touch;function Touch(){this.dragging=false;if(Glide.options.touchDistance){Glide.track.on({'touchstart.glide':$.proxy(this.start,this)});}
if(Glide.options.dragDistance){Glide.track.on({'mousedown.glide':$.proxy(this.start,this)});}}
Touch.prototype.unbind=function(){Glide.track.off('touchstart.glide mousedown.glide').off('touchmove.glide mousemove.glide').off('touchend.glide touchcancel.glide mouseup.glide mouseleave.glide');};Touch.prototype.start=function(event){if(!Core.Events.disabled&&!this.dragging){if(event.type==='mousedown'){touch=event.originalEvent;}else{touch=event.originalEvent.touches[0]||event.originalEvent.changedTouches[0];}
Core.Transition.jumping=true;this.touchStartX=parseInt(touch.pageX);this.touchStartY=parseInt(touch.pageY);this.touchSin=null;this.dragging=true;Glide.track.on({'touchmove.glide mousemove.glide':Core.Helper.throttle($.proxy(this.move,this),Glide.options.throttle),'touchend.glide touchcancel.glide mouseup.glide mouseleave.glide':$.proxy(this.end,this)});Core.Events.detachClicks().call(Glide.options.swipeStart).trigger('swipeStart');Core.Run.pause();}};Touch.prototype.move=function(event){if(!Core.Events.disabled&&this.dragging){if(event.type==='mousemove'){touch=event.originalEvent;}else{touch=event.originalEvent.touches[0]||event.originalEvent.changedTouches[0];}
var subExSx=parseInt(touch.pageX)-this.touchStartX;var subEySy=parseInt(touch.pageY)-this.touchStartY;var powEX=Math.abs(subExSx<<2);var powEY=Math.abs(subEySy<<2);var touchHypotenuse=Math.sqrt(powEX+powEY);var touchCathetus=Math.sqrt(Core.Helper.byAxis(powEY,powEX));this.touchSin=Math.asin(touchCathetus/touchHypotenuse);this.distance=Core.Helper.byAxis((touch.pageX-this.touchStartX),(touch.pageY-this.touchStartY));if((this.touchSin*180/Math.PI)<45){Core.Animation.make(Core.Helper.byAxis(subExSx,subEySy));}
Core.Events.preventClicks().call(Glide.options.swipeMove).trigger('swipeMove');if(Core.Build.isMode('vertical')){if(Core.Run.isStart()&&subEySy>0){return;}
if(Core.Run.isEnd()&&subEySy<0){return;}}
if((this.touchSin*180/Math.PI)<45){event.stopPropagation();event.preventDefault();Glide.track.addClass(Glide.options.classes.dragging);}else{return;}}};Touch.prototype.end=function(event){if(!Core.Events.disabled&&this.dragging){var distanceLimiter;if(event.type==='mouseup'||event.type==='mouseleave'){touch=event.originalEvent;}else{touch=event.originalEvent.touches[0]||event.originalEvent.changedTouches[0];}
var touchDistance=Core.Helper.byAxis((touch.pageX-this.touchStartX),(touch.pageY-this.touchStartY));var touchDeg=this.touchSin*180/Math.PI;Core.Transition.jumping=false;if(Core.Build.isType('slider')){if(Core.Run.isStart()){if(touchDistance>0){touchDistance=0;}}
if(Core.Run.isEnd()){if(touchDistance<0){touchDistance=0;}}}
if(event.type==='mouseup'||event.type==='mouseleave'){distanceLimiter=Glide.options.dragDistance;}else{distanceLimiter=Glide.options.touchDistance;}
if(touchDistance>distanceLimiter&&touchDeg<45){Core.Run.make('<');}
else if(touchDistance<-distanceLimiter&&touchDeg<45){Core.Run.make('>');}
else{Core.Animation.make();}
Core.Animation.after(function(){Core.Events.enable();Core.Run.play();});this.dragging=false;Core.Events.attachClicks().disable().call(Glide.options.swipeEnd).trigger('swipeEnd');Glide.track.removeClass(Glide.options.classes.dragging).off('touchmove.glide mousemove.glide').off('touchend.glide touchcancel.glide mouseup.glide mouseleave.glide');}};return new Touch();};;var Transition=function(Glide,Core){function Transition(){this.jumping=false;}
Transition.prototype.get=function(property){if(!this.jumping){return property+' '+Glide.options.animationDuration+'ms '+Glide.options.animationTimingFunc;}
return this.clear('all');};Transition.prototype.clear=function(property){return property+' 0ms '+Glide.options.animationTimingFunc;};return new Transition();};;var Translate=function(Glide,Core){var axes={x:0,y:0,z:0};function Translate(){}
Translate.prototype.set=function(axis,value){axes[axis]=parseInt(value);return'translate3d('+(-1*axes.x)+'px, '+(-1*axes.y)+'px, '+(-1*axes.z)+'px)';};return new Translate();};;var Glide=function(element,options){var defaults={autoplay:4000,type:'carousel',mode:'horizontal',startAt:1,hoverpause:true,keyboard:true,touchDistance:80,dragDistance:120,animationDuration:400,animationTimingFunc:'cubic-bezier(0.165, 0.840, 0.440, 1.000)',throttle:16,autoheight:false,paddings:0,centered:true,classes:{base:'glide',wrapper:'glide__wrapper',track:'glide__track',slide:'glide__slide',arrows:'glide__arrows',arrow:'glide__arrow',arrowNext:'next',arrowPrev:'prev',bullets:'glide__bullets',bullet:'glide__bullet',clone:'clone',active:'active',dragging:'dragging',disabled:'disabled'},beforeInit:function(event){},afterInit:function(event){},beforeTransition:function(event){},duringTransition:function(event){},afterTransition:function(event){},swipeStart:function(event){},swipeEnd:function(event){},swipeMove:function(event){},};this.options=$.extend({},defaults,options);this.uuid=Math.floor(Math.random()*1000);this.current=parseInt(this.options.startAt);this.element=element;this.collect();this.setup();this.destroyed=false;this.options.beforeInit({index:this.current,length:this.slides.length,current:this.slides.eq(this.current-1),slider:this.slider});var Engine=new Core(this,{Helper:Helper,Translate:Translate,Transition:Transition,Arrows:Arrows,Bullets:Bullets,Run:Run,Animation:Animation,Clones:Clones,Height:Height,Build:Build,Events:Events,Touch:Touch,Api:Api});Engine.Events.call(this.options.afterInit);return Engine.Api.instance();};Glide.prototype.collect=function(){var options=this.options;var classes=options.classes;this.slider=this.element.addClass(classes.base+'--'+options.type).addClass(classes.base+'--'+options.mode);this.track=this.slider.find('.'+classes.track);this.wrapper=this.slider.find('.'+classes.wrapper);this.slides=this.track.find('.'+classes.slide).not('.'+classes.clone);};Glide.prototype.setup=function(){var modeToDimensionsMap={horizontal:['width','x'],vertical:['height','y'],};this.size=modeToDimensionsMap[this.options.mode][0];this.axis=modeToDimensionsMap[this.options.mode][1];this.length=this.slides.length;this.paddings=this.getPaddings();this[this.size]=this.getSize();};Glide.prototype.getPaddings=function(){var option=this.options.paddings;if(typeof option==='string'){var normalized=parseInt(option,10);var isPercentage=option.indexOf('%')>=0;if(isPercentage){return parseInt(this.slider[this.size]()*(normalized/100));}
return normalized;}
return option;};Glide.prototype.getSize=function(){return this.slider[this.size]()-(this.paddings*2);};;$.fn.glide=function(options){return this.each(function(){if(!$.data(this,'glide_api')){$.data(this,'glide_api',new Glide($(this),options));}});};})(jQuery,window,document);
